const data = window.PORTFOLIO;
const choices = ['minimal', 'lab', 'editorial', 'dashboard', 'timeline'];
const requested = new URLSearchParams(location.search).get('theme');
const theme = choices.includes(requested) ? requested : 'minimal';
document.body.dataset.theme = theme;

const safe = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const name = safe(data.name);
const roles = data.capabilities.map(item => `<div><small>${safe(item.label)}</small><strong>${safe(item.value)}</strong></div>`).join('');
const work = data.experience.map(item => `<article class="work-item"><span>${safe(item.number)}</span><div><small>${safe(item.type)}</small><h3>${safe(item.title)}</h3><p>${safe(item.description)}</p></div></article>`).join('');
const milestones = data.milestones.map(item => `<article class="milestone"><span>${safe(item.year)}</span><div><h3>${safe(item.title)}</h3><p>${safe(item.text)}</p></div></article>`).join('');

const linkConfig = [
  ['email', '電子郵件', value => `mailto:${encodeURIComponent(value)}`],
  ['linkedin', 'LinkedIn', value => value],
  ['github', 'GitHub', value => value],
  ['resume', '下載履歷', value => value]
];
const contactLinks = linkConfig.flatMap(([key,label,url]) => {
  const value = data.links?.[key]?.trim();
  if (!value) return [];
  if (key !== 'email' && !/^https?:\/\//i.test(value) && !/^\.\.?\//.test(value)) return [];
  return [`<a href="${safe(url(value))}" ${key === 'email' ? '' : 'target="_blank" rel="noopener noreferrer"'}>${label} ↗</a>`];
}).join('');
const contact = contactLinks ? `<section class="site-contact" id="contact"><span>CONTACT / 聯絡</span><h2>讓我們聊聊資料與問題。</h2><div>${contactLinks}</div></section>` : '';
const topLinks = `<a class="site-skip" href="#content">跳到主要內容</a><a class="back-gallery" href="templates.html">← 五款模板</a>`;
const footer = `<footer class="template-footer"><span>${name} · ${safe(data.role)}</span><a href="templates.html">查看其他四款 ↗</a></footer>`;

const pages = {
  minimal: () => `<div class="minimal-page">${topLinks}<header class="minimal-nav"><strong>${name}<i>.</i></strong><nav><a href="#experience">經驗</a><a href="#capabilities">能力</a><a href="#about">關於</a>${contactLinks ? '<a href="#contact">聯絡</a>' : ''}</nav></header><main id="content"><section class="minimal-hero"><div><span class="eyebrow">HELLO / ABOUT ME</span><h1>用分析<br>理解問題<span>。</span></h1><p class="hero-lead">${safe(data.lead)}</p><a class="primary-link" href="#experience">看我的工作內容 <b>↘</b></a></div><aside class="minimal-profile"><div class="profile-monogram" aria-hidden="true">${safe(data.initials)}</div><span>PROFILE / 001</span><h2>${name}</h2><p>${safe(data.role)}</p><dl><div><dt>背景</dt><dd>${safe(data.education)}</dd></div><div><dt>所在地</dt><dd>${safe(data.location)}</dd></div></dl></aside></section><section class="minimal-section" id="experience"><div class="section-label">01 / EXPERIENCE</div><div><h2>從資料出發，<br>把觀察說清楚。</h2><div class="work-list">${work}</div></div></section><section class="minimal-section" id="capabilities"><div class="section-label">02 / CAPABILITIES</div><div><h2>我帶著這些工具<br>與習慣工作。</h2><div class="capability-grid">${roles}</div></div></section><section class="minimal-about" id="about"><span>03 / ABOUT</span><p>${safe(data.intro)}</p><blockquote>${safe(data.approach)}</blockquote></section>${contact}</main>${footer}</div>`,

  lab: () => `<div class="lab-page">${topLinks}<aside class="lab-rail"><a href="#content" class="rail-brand">LD<span>_</span></a><nav><a href="#work">WORK</a><a href="#method">METHOD</a><a href="#skills">TOOLS</a></nav><span>TAIWAN / ${new Date().getFullYear()}</span></aside><main id="content" class="lab-main"><div class="lab-status"><span class="signal"></span> PERSONAL DATA LAB <span class="lab-id">PROFILE / ${name}</span></div><section class="lab-hero"><small>MATHEMATICS × INSURANCE × ANALYTICS</small><h1>把複雜的資料，<br><em>變成清楚的判斷。</em></h1><p>${safe(data.intro)}</p><a href="#work">探索工作紀錄 <span>↘</span></a><div class="lab-orbit" aria-hidden="true"><i></i><i></i><i></i><b>DATA<br>→<br>INSIGHT</b></div></section><section class="lab-work" id="work"><div class="lab-heading"><span>01 / SELECTED PRACTICE</span><h2>實務工作</h2></div><div class="lab-work-grid">${data.experience.map(item => `<article><small>${safe(item.number)} / ${safe(item.type)}</small><h3>${safe(item.title)}</h3><p>${safe(item.description)}</p><span class="lab-arrow">↗</span></article>`).join('')}</div></section><section class="lab-method" id="method"><span>02 / HOW I WORK</span><h2>一個能被討論的分析，<br>從正確提問開始。</h2><div class="method-steps"><div><b>01</b><strong>定義</strong><p>釐清問題與資料口徑</p></div><div><b>02</b><strong>拆解</strong><p>檢視差異與可能原因</p></div><div><b>03</b><strong>說明</strong><p>整理觀察與行動方向</p></div></div></section><section class="lab-skills" id="skills"><span>03 / TOOLBOX</span><div>${roles}</div></section>${contact}${footer}</main></div>`,

  editorial: () => `<div class="editorial-page">${topLinks}<header class="editorial-mast"><a href="#content">${name} / NOTES</a><span>PERSONAL ISSUE · VOL. 01</span><nav><a href="#stories">經歷</a><a href="#profile">關於</a></nav></header><main id="content"><section class="editorial-cover"><div class="editorial-issue">數學、資料<br>與工作現場<br><span>— 一份個人誌</span></div><h1>在數字之間，<br><em>找到可以說明的事。</em></h1><div class="editorial-sub"><p>${safe(data.lead)}</p><span>WORDS & ANALYSIS<br>${name}</span></div></section><section class="editorial-intro" id="profile"><span>OPENING NOTE / 01</span><div><h2>你好，<br>我是${name}。</h2><p>${safe(data.intro)}</p></div><blockquote>「${safe(data.approach)}」</blockquote></section><section class="editorial-stories" id="stories"><div class="editorial-section-title"><span>WORK / 02</span><h2>工作中的三種提問</h2></div><div class="editorial-articles">${data.experience.map(item => `<article><small>QUESTION ${safe(item.number)} / ${safe(item.type)}</small><h3>${safe(item.title)}</h3><p>${safe(item.description)}</p></article>`).join('')}</div></section><section class="editorial-end"><span>FIELD NOTES / 03</span><h2>下一頁，繼續把問題問好。</h2><p>${safe(data.education)}。我持續深化統計與資料分析能力，並在實務中練習讓結論更清楚。</p><div class="editorial-skills">${data.capabilities.map(item => `<span>${safe(item.label)}：${safe(item.value)}</span>`).join('')}</div></section>${contact}</main>${footer}</div>`,

  dashboard: () => `<div class="dashboard-page">${topLinks}<aside class="dash-side"><div class="dash-logo">L<span>D</span></div><span>PERSONAL ANALYTICS</span><nav><a href="#overview">◫　總覽</a><a href="#practice">▤　實務經驗</a><a href="#process">◈　工作方式</a><a href="#toolkit">⌘　能力工具</a></nav><div class="dash-side-bottom">${name}<br><small>${safe(data.role)}</small></div></aside><main id="content" class="dash-main"><header><span>PERSONAL DASHBOARD / OVERVIEW</span><a href="templates.html">其他版型 ↗</a></header><section id="overview" class="dash-hero"><div><small>WELCOME TO MY WORKSPACE</small><h1>你好，我是${name}。</h1><p>${safe(data.intro)}</p><a href="#practice">查看我的實務經驗 ↘</a></div><div class="dash-disc" aria-hidden="true"><span>ANALYZE<br>EXPLAIN<br>IMPROVE</span></div></section><div class="dash-summary"><article><span>FOCUS / 01</span><strong>商品表現</strong><small>損失率與獲利觀察</small></article><article><span>TOOLS / 02</span><strong>資料處理</strong><small>SAS、SQL、R、Python</small></article><article><span>WORK / 03</span><strong>跨部門協作</strong><small>將分析轉成共同語言</small></article></div><section id="practice" class="dash-panel"><div class="dash-panel-head"><span>01 / PRACTICE</span><h2>實務經驗</h2></div><div class="dash-rows">${data.experience.map(item => `<article><b>${safe(item.number)}</b><div><h3>${safe(item.title)}</h3><p>${safe(item.description)}</p></div><small>${safe(item.type)}</small></article>`).join('')}</div></section><div class="dash-bottom"><section id="process" class="dash-panel"><div class="dash-panel-head"><span>02 / PROCESS</span><h2>分析流程</h2></div><div class="dash-process"><div><i></i><span>問題定義</span></div><div><i></i><span>資料檢視</span></div><div><i></i><span>原因拆解</span></div><div><i></i><span>結論溝通</span></div></div><p>${safe(data.approach)}</p></section><section id="toolkit" class="dash-panel"><div class="dash-panel-head"><span>03 / TOOLKIT</span><h2>能力與工具</h2></div><div class="dash-capabilities">${roles}</div></section></div>${contact}${footer}</main></div>`,

  timeline: () => `<div class="timeline-page">${topLinks}<header class="timeline-nav"><a href="#content">${name}<span> / JOURNEY</span></a><nav><a href="#journey">歷程</a><a href="#practice">實務</a><a href="#focus">方向</a></nav></header><main id="content"><section class="timeline-hero"><span>GROWTH IS A SERIES OF QUESTIONS</span><h1>從數學出發，<br>走向<span>資料的現場。</span></h1><p>${safe(data.lead)}</p><div class="timeline-hero-line" aria-hidden="true"><i></i><i></i><i></i></div></section><section id="journey" class="journey"><div class="journey-intro"><span>01 / MY JOURNEY</span><h2>每一步，<br>都讓問題更清楚。</h2><p>${safe(data.intro)}</p></div><div class="journey-items">${milestones}</div></section><section id="practice" class="timeline-practice"><div><span>02 / IN PRACTICE</span><h2>把學到的，<br>用在工作裡。</h2></div><div class="timeline-work">${work}</div></section><section id="focus" class="timeline-focus"><span>03 / WHAT I VALUE</span><h2>謹慎思考，持續修正。</h2><p>${safe(data.approach)}</p><div>${data.capabilities.map(item => `<article><small>${safe(item.label)}</small><strong>${safe(item.value)}</strong></article>`).join('')}</div></section>${contact}</main>${footer}</div>`
};

document.title = `${data.name}｜${({minimal:'清晰履歷',lab:'資料實驗室',editorial:'個人誌',dashboard:'分析面板',timeline:'學習路徑'})[theme]}`;
document.querySelector('#site-root').innerHTML = pages[theme]();
